spring:
  application:
    name: hr
  profiles:
    active: smart

hr:
  raise:
    smart:
      years:
        low: 2.5
        mid: 5
        high: 10
        highpercent: 10
        highmidpercent: 5
        midlowpercent: 2
        lowpercent: 0